### ISSUE TITLE
cookiecutter not found while creating a new project

### ISSUE THREAD

**Issue by kpdkaran** [beeware/vscode-beeware#27]
On start of the BeeWare: Create a New Project in VS Code, I get this error: 'Failed to install 'cookiecutter' into c:\Users\User\.vscode-insiders\extensions\beeware.beeware-0.0.1\python_files\packages, please install manually'.
I have tried many ways to put cookiecutter in those folder but unable to make it work. Kindly Help!
Thanks a Lot in Advance!!

**Comment by luni222** [comment]
Type "alias pip=pip3" in the terminal, then "sudo pip3 install --upgrade pip" and then click at VSCode CTRL + LSHIFT + P and type "Beeware: Create a new Project" - it will work now. I was looking for the solution for almost whole day, and all I had to do was to look at Developer Tools, because in the Console there was written that "pip was not found".

**Comment by richierh** [comment]
it s not working for what @luni222  suggested....

**Comment by longswordinhand** [comment]
I have the same problem in VS code insider + Win10. I upgrade the pip and create a new project again. I also manually install cookiecutter. Same problem. Please help. Thanks.

**Comment by aleksas** [comment]
+

**Comment by freakboy3742** [comment]
Closing; we're archiving this project.
