### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by kryptonianson** [beeware/vscode-beeware#31]
Noticing this has not been touched in a very long time. Is this project dead? Thank you :)

**Comment by freakboy3742** [comment]
Not dead... just resting :-)

It hasn't been updated for a long time, partially because we've been focussing on changes to Briefcase itself; partially because the person who originally contributed this plugin has moved on to other things; and partially because those who use maintain Briefcase weren't active users of the plugin.

If someone is motivated to maintain it, we'd love to see it updated for Briefcase 0.3.

Closing procedurally; if you've got any other questions, we're happy to answer them here, or on another ticket.

**Comment by DonJayamanne** [comment]
> we'd love to see it updated for Briefcase 0.3.

I'll try that out this week, around friday.
